# Generated by Django 3.0.6 on 2020-05-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='company',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
