# Generated by Django 3.0.6 on 2020-05-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_customers_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
